### ISSUE TITLE
beginner question with downloading nmssg project, framework red

### ISSUE THREAD

**Issue by solarissf** [Lejdborg/NMSSH#115] opened 2015-02-22 00:22 UTC
i apologize for such a basic question, but I downloaded the full project of this site.  I am following the tutorial to bring it into my existing app and am stuck halfway through.  I downloaded the project.  Hit build like in the tutorial.  Now I go to copy the framework to my existing project, and it says.. error , framework does not exist.  also the framework itself is a red color like it didn't properly build or something.

am I missing something simple about copying your framework into my existing project?

thanks in advance

**Comment by bhr** [comment] 2015-02-23 00:23
Did you look up if the framework has been built correctly? Just go into `NMSSH/Producs` in Finder.app and you should see `NMSSH.framework`. If not, building NMSSH didn't succeed. Verify that you have set the correct target, build again, and look if the file framework is now there. Now, you can drag this file into your Xcode project and continue with the steps from the Wiki (https://github.com/Lejdborg/NMSSH/wiki/Build-and-use-in-your-iOS-project)

**Comment by solarissf** [comment] 2015-02-23 02:41
in my finder app... under is no nmssh.framework... even if i do a search under the home finder screen. so that must mean i am not building it correctly.  so how do I do that.  no matter what i click on and hit build... the framework always stays red.  is there something I am missing to building a project?

**Comment by solarissf** [comment] 2015-02-23 15:24
so it looks like the framework I have was build for device.  I need to rebuild for simulator while I build the app.  Can you please show me how to do this?

**Comment by bhr** [comment] 2015-02-23 16:06
It's hard to guess what is actually going wrong on your end. The framework should work on both simulator and device.

Here's what I suggest you'd try first:
- go to NMSSH folder
- delete `Products` folder
- open `NMSSH-iOS.xcodeproj`
- select `NMSSH Framework` as target
- build the framework
- verify that framework is where it should be
- open `PTYExample.xcodeproj` under `Examples/PTYExample/`
- verify that Framework is not marked as `not found` in Xcode in `PTYExample.xcodeproj`
- build and run on simulator --> should work.

If that doesn't work, we need to look where the issue is. If Xcode throws any errors while building, please post them here.

Another idea may be to use CocoaPods instead of manually adding NMSSH to your project.

**Comment by solarissf** [comment] 2015-02-23 18:45
so I'm not exactly sure how... but it works now.  your steps above worked.
my next NOOB question will be posted in a new thread

thanks!

**Closed** 2015-02-23 18:46 UTC
